"""Direct HDF5/XML surgery on the bundled HEC-RAS 2025 template project.

The template (hype_app/data/ras_template) is a complete, solvable RAS 2025 project whose
2D flow area is defined by a *conceptual mesh*: 4 corner Nodes joined by 4 Arcs (upstream,
left bank, downstream, right bank). Everything under `/Geometry/2D Flow Areas/*` — the
computed mesh, perimeter and property tables — is REGENERATED by `ras mesh` / the solver's
prepare step from that topology, so a repack only rewrites:

  Geometry.h5   /Geometry/Mesh Topology  (Nodes, Arc Internal Points, Arc Attributes.Count,
                Control Points, Control Point Attributes.ConstantSize)
  Boundary Condition.h5  BC line polylines, constant Flow / Normal Depth payloads, and the
                Start/End time window (Time Window Mode = BoundaryCondition: the BC window
                is what actually sets the run duration)
  Plan.h5       timestep / output-interval / duration attributes
  N Values.h5   constant Manning's n
  *.h5 root     Project Projection (WKT) + Project Units ("SI")
  MinkBrook.ras <Projection Type="EPSG"> value

Template arc layout (fixed; preserved by the repack):
  Nodes  N0=up-right  N1=up-left  N2=down-left  N3=down-right   (relative to flow)
  Arcs   arc0 = N0->N1 upstream edge      (the "Upstream" BC line lies on it)
         arc1 = N1->N2 left bank, up->down
         arc2 = N2->N3 downstream edge    (the "Boundary Condition Line 1" BC line)
         arc3 = N3->N0 right bank, down->up

HDF5 gotcha: h5py/HDF5's NULLTERM string conversion silently truncates strings that
exactly fill their fixed width (e.g. Variable 'Normal Depth' S12, Recipe 'Default()' S9)
on ANY dataset write that includes the field — so compound datasets are only ever written
one numeric field at a time, never round-tripped whole.
"""
from __future__ import annotations

import datetime as _dt
import re
from pathlib import Path

import numpy as np

# .NET ticks: 100 ns units since 0001-01-01T00:00:00 (UTC here). RAS 2025 stores all
# times (BC window, plan start, timestep, output interval) in this encoding.
_TICKS_PER_SECOND = 10_000_000
_UNIX_EPOCH_TICKS = 62_135_596_800 * _TICKS_PER_SECOND


def datetime_to_ticks(dt: _dt.datetime) -> int:
    return int(dt.timestamp() * _TICKS_PER_SECOND) + _UNIX_EPOCH_TICKS


def seconds_to_ticks(seconds: float) -> int:
    return int(round(seconds * _TICKS_PER_SECOND))


def _desc_time(dt: _dt.datetime) -> str:
    """Match the template's human-readable companion attrs, e.g. '1/1/2099 12:00:00 AM'."""
    hour12 = dt.hour % 12 or 12
    ampm = "AM" if dt.hour < 12 else "PM"
    return f"{dt.month}/{dt.day}/{dt.year} {hour12}:{dt.minute:02d}:{dt.second:02d} {ampm}"


def _desc_interval(seconds: float) -> str:
    s = int(round(seconds))
    return f"{s // 3600:02d}:{(s % 3600) // 60:02d}:{s % 60:02d}"


def _set_attr_like(attrs, key, value):
    """Replace an attribute, preserving the stored numpy dtype kind (fixed bytes vs numeric)."""
    old = attrs.get(key)
    if isinstance(value, str):
        attrs[key] = np.bytes_(value)
    elif old is not None and hasattr(old, "dtype"):
        attrs[key] = np.asarray(value, dtype=old.dtype)
    else:
        attrs[key] = value


def write_root_attrs(h5_path, *, wkt: str, units: str = "SI", project_name: str | None = None):
    """Set the Project Projection / Project Units (+ optionally Project Name) root attrs."""
    import h5py

    with h5py.File(h5_path, "r+") as f:
        f.attrs["Project Projection"] = np.bytes_(wkt)
        f.attrs["Project Units"] = np.bytes_(units)
        if project_name:
            f.attrs["Project Name"] = np.bytes_(project_name)


def rewrite_ras_xml(ras_path, epsg: int):
    """Point the project's <Projection Type="EPSG"> at the model CRS."""
    p = Path(ras_path)
    xml = p.read_text(encoding="utf-8")
    xml, n = re.subn(r'(<Projection Type="EPSG">)\d+(</Projection>)',
                     rf"\g<1>{epsg}\g<2>", xml)
    if n != 1:
        raise ValueError(f"Expected exactly one EPSG Projection element in {ras_path}, found {n}")
    p.write_text(xml, encoding="utf-8")


def _replace_dataset(group, name, data, attrs: dict):
    """Delete-and-recreate a plain (non-compound) dataset whose shape changes between runs."""
    data = np.asarray(data, dtype=np.float64)
    if name in group:
        del group[name]
    d = group.create_dataset(name, data=data, maxshape=tuple(None for _ in data.shape))
    for k, v in attrs.items():
        d.attrs[k] = v
    return d


def write_geometry_topology(geometry_h5, sides_xy: dict, cell_size: float):
    """Rewrite the conceptual mesh from the app's four boundary lines.

    ``sides_xy`` holds the oriented model-CRS coordinate arrays from
    ``geometry.assemble_domain_from_sides`` (after projection): ``up``/``down`` run
    left->right, ``left``/``right`` run upstream->downstream, with snapped shared corners.
    """
    import h5py

    up = np.asarray(sides_xy["up"], dtype=np.float64)
    down = np.asarray(sides_xy["down"], dtype=np.float64)
    left = np.asarray(sides_xy["left"], dtype=np.float64)
    right = np.asarray(sides_xy["right"], dtype=np.float64)

    # Template arc order/direction (see module docstring): N0=UR N1=UL N2=DL N3=DR.
    nodes = np.vstack([up[-1], up[0], down[0], down[-1]])
    arcs = [up[::-1], left, down, right[::-1]]           # arc i runs N_i -> N_(i+1)%4

    internal, counts, starts = [], [], []
    arc_cell_counts = np.zeros(4, dtype=np.int32)
    for i, pts in enumerate(arcs):
        interior = pts[1:-1]
        starts.append(len(internal))
        counts.append(len(interior))
        internal.extend(interior.tolist())
        seglen = float(np.hypot(*np.diff(pts, axis=0).T).sum())
        arc_cell_counts[i] = max(2, int(round(seglen / cell_size)))
    internal = np.asarray(internal, dtype=np.float64).reshape(-1, 2)

    with h5py.File(geometry_h5, "r+") as f:
        mt = f["Geometry/Mesh Topology"]
        conn = mt["Arc Connectivity"][...]
        expected = np.array([[0, 1], [1, 2], [2, 3], [3, 0]], dtype=conn.dtype)
        if not np.array_equal(conn, expected):
            raise ValueError(f"Template Arc Connectivity changed: {conn.tolist()}")
        mt["Nodes"][...] = nodes
        _replace_dataset(mt, "Arc Internal Points", internal, {
            "Count": np.asarray(counts, dtype=np.int32),
            "Start": np.asarray(starts, dtype=np.int32),
        })
        # numeric single-field writes only (string-truncation gotcha; see module docstring)
        mt["Arc Attributes"]["Count"] = arc_cell_counts
        mt["Control Points"][...] = np.mean(nodes, axis=0, keepdims=True)
        mt["Control Point Attributes"]["ConstantSize"] = np.asarray([cell_size], dtype=np.float32)
    return {"arc_cell_counts": arc_cell_counts.tolist(), "n_internal_points": int(len(internal))}


def write_bc_lines(bc_h5, *, up_xy, down_xy, flow_cms: float, friction_slope: float,
                   start: _dt.datetime, duration_s: float):
    """Rewrite the two BC line polylines (on the upstream/downstream arcs), the constant
    Flow / Normal Depth payload values, and the BC time window (which sets the run length)."""
    import h5py

    up_xy = np.asarray(up_xy, dtype=np.float64)
    down_xy = np.asarray(down_xy, dtype=np.float64)
    end = start + _dt.timedelta(seconds=duration_s)

    with h5py.File(bc_h5, "r+") as f:
        g = f["Boundary Conditions"]
        names = [bytes(n) for n in g["BC Lines/Attributes"]["Name"]]
        if names != [b"Upstream", b"Boundary Condition Line 1"]:
            raise ValueError(f"Template BC line names changed: {names}")
        _replace_dataset(g["BC Lines"], "Polyline", np.vstack([up_xy, down_xy]), {
            "Count": np.asarray([len(up_xy), len(down_xy)], dtype=np.int32),
            "Start": np.asarray([0, len(up_xy)], dtype=np.int32),
        })
        pay = g["BC Lines/Payloads/Payloads"]
        variables = [bytes(v) for v in pay["Variable"]]
        if variables != [b"Flow", b"Normal Depth"]:
            raise ValueError(f"Template payload variables changed: {variables}")
        pay["Constant"] = np.asarray([flow_cms, friction_slope], dtype=np.float64)
        _set_attr_like(g.attrs, "Start Time", datetime_to_ticks(start))
        _set_attr_like(g.attrs, "End Time", datetime_to_ticks(end))
        _set_attr_like(g.attrs, "Start Time (DESC)", _desc_time(start))
        _set_attr_like(g.attrs, "End Time (DESC)", _desc_time(end))


def write_plan_attrs(plan_h5, *, start: _dt.datetime, duration_s: float,
                     timestep_s: float, output_interval_s: float):
    """Plan solver-control attrs. Solver stays CPU (template value; the CLI also passes
    --solver CPU). The BC window governs the run length (Time Window Mode=BoundaryCondition)
    but the plan's start/duration are kept consistent with it.

    Equation Set is forced to explicit Shallow Water: the template's Diffusion Wave solver
    needs a sparse matrix backend — Pardiso/MKL on Windows, but on Linux the managed-PCG
    fallback diverges instantly (Courant abort). SolverExpSWE is matrix-free and runs
    identically on both platforms (and is the fuller-physics option anyway)."""
    import h5py

    with h5py.File(plan_h5, "r+") as f:
        a = f["Plan Data"].attrs
        _set_attr_like(a, "Solver", "CPU")
        _set_attr_like(a, "Equation Set", "Shallow Water Equations")
        _set_attr_like(a, "Time-stepping", "Explicit")
        _set_attr_like(a, "Compute Start Time", datetime_to_ticks(start))
        _set_attr_like(a, "Compute Start Time (DESC)", _desc_time(start))
        _set_attr_like(a, "Compute Duration", float(duration_s))
        _set_attr_like(a, "Base Compute Timestep", seconds_to_ticks(timestep_s))
        _set_attr_like(a, "Base Compute Timestep (DESC)", _desc_interval(timestep_s))
        _set_attr_like(a, "Base Output Interval", seconds_to_ticks(output_interval_s))
        _set_attr_like(a, "Base Output Interval (DESC)", _desc_interval(output_interval_s))


def write_n_values(nvalues_h5, manning_n: float):
    import h5py

    with h5py.File(nvalues_h5, "r+") as f:
        _set_attr_like(f["NValues"].attrs, "Constant Value", np.float32(manning_n))


def read_mesh_summary(geometry_h5) -> dict:
    """Post-`ras mesh` sanity data: cell count + perimeter bbox."""
    import h5py

    with h5py.File(geometry_h5, "r") as f:
        att = f["Geometry/2D Flow Areas/Attributes"][...]
        per = f["Geometry/2D Flow Areas/Mesh/Perimeter"][...]
        return {
            "cell_count": int(att["Cell Count"][0]),
            "perimeter_bbox": (*per.min(axis=0).tolist(), *per.max(axis=0).tolist()),
        }


def read_compute_summary(result_h5) -> dict:
    """Success flag + last output time from a RAS result file."""
    import h5py

    with h5py.File(result_h5, "r") as f:
        cs = dict(f["Results/Compute Summary"].attrs)
        t = f["Results/Output Blocks/Base Output/Time"][...]
        depth = f["Results/Output Blocks/Base Output/2D Flow Areas/Mesh/Cell Depth"]
        return {
            "success": bool(int(cs.get("Computed Successfully", 0))),
            "profiles": int(len(t)),
            "max_depth_last": float(depth[-1].max()) if len(t) else 0.0,
            "log": (cs.get("Compute Log", b"") or b"").decode("utf-8", "replace")
                   if isinstance(cs.get("Compute Log"), bytes) else str(cs.get("Compute Log", "")),
        }
